<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE9XTDAk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE9XTDAk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE9XTDAk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE9XTDAk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE9XTDAk\App_KernelDevDebugContainer([
    'container.build_hash' => 'E9XTDAk',
    'container.build_id' => '9a2bdcb0',
    'container.build_time' => 1733861767,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE9XTDAk');
