<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ0xU9KW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ0xU9KW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ0xU9KW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ0xU9KW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ0xU9KW\App_KernelDevDebugContainer([
    'container.build_hash' => 'J0xU9KW',
    'container.build_id' => 'ba225366',
    'container.build_time' => 1730743126,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ0xU9KW');
